/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blacklistedTokenSol from "./BlacklistedToken.sol";
export type { blacklistedTokenSol };
import type * as fixedSupplyTokenSol from "./FixedSupplyToken.sol";
export type { fixedSupplyTokenSol };
import type * as tetherSol from "./Tether.sol";
export type { tetherSol };
export type { AlwaysFalseERC165 } from "./AlwaysFalseERC165";
export type { Fail } from "./Fail";
export type { ForwarderTarget } from "./ForwarderTarget";
export type { GasGuzzler } from "./GasGuzzler";
export type { GasHeavy } from "./GasHeavy";
export type { MockERC1155 } from "./MockERC1155";
export type { MockERC721 } from "./MockERC721";
export type { Reentry } from "./Reentry";
export type { ReentryForwarder } from "./ReentryForwarder";
export type { ReentryWalletSimple } from "./ReentryWalletSimple";
export type { TestBatcherDriver } from "./TestBatcherDriver";
