/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RecoveryWalletFactory__factory } from "./RecoveryWalletFactory__factory";
export { RecoveryWalletSimple__factory } from "./RecoveryWalletSimple__factory";
