/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArbethWalletSimple } from "./ArbethWalletSimple";
export type { CeloWalletSimple } from "./CeloWalletSimple";
export type { EtcWalletSimple } from "./EtcWalletSimple";
export type { OpethWalletSimple } from "./OpethWalletSimple";
export type { PolygonWalletSimple } from "./PolygonWalletSimple";
export type { RskWalletSimple } from "./RskWalletSimple";
export type { ZkethWalletSimple } from "./ZkethWalletSimple";
