/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ArbethWalletSimple__factory } from "./ArbethWalletSimple__factory";
export { CeloWalletSimple__factory } from "./CeloWalletSimple__factory";
export { EtcWalletSimple__factory } from "./EtcWalletSimple__factory";
export { OpethWalletSimple__factory } from "./OpethWalletSimple__factory";
export { PolygonWalletSimple__factory } from "./PolygonWalletSimple__factory";
export { RskWalletSimple__factory } from "./RskWalletSimple__factory";
export { ZkethWalletSimple__factory } from "./ZkethWalletSimple__factory";
