name: Create Release on Push Tag
on:
 push:
   tags:
      - 'r*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run test
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      - run: npm run deploy-test
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      - name: Create Release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const fs = require('fs');
              const path = require('path');
              var json;
              var html = "";
              try {
                json = JSON.parse(fs.readFileSync('./output.json').toString());
                for(const key in json){
                  html += key+": "+json[key]+"<br>";
                }
              } catch (err){
                console.log("error converting json to html."+ err);
              }
              const repo = context.repo.repo;
              const owner = context.repo.owner;
              const tag = process.env.GITHUB_REF_NAME;
              const release= await github.rest.repos.createRelease({
                owner,
                repo,
                tag_name: tag,
                body: html,
                prerelease: true
              });
