on: push

env:
  PRIVATE_KEY: ${{secrets.API_KEY}}
  ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: yarn
      - run: npm test


