name: Lint and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  lint-and-test:
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run test
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
    - run: npm run lint
