/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FixedSupplyToken__factory } from "./FixedSupplyToken__factory";
export { IERC20__factory } from "./IERC20__factory";
